---
builds:
  - env:
      - CGO_ENABLED=0

    ldflags:
      - "-s"
      - "-w"
      - "-extldflags '-static'"
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{.Date}}"

    goos:
      - linux

    goarch:
      - amd64
      - arm64
      - 386
      - arm

    goarm:
      - 5
      - 6
      - 7

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^ci"
      - "^lint"
      - "^meta"
      - "^deployment"
      - "^build"
      - "happy linting"
      - "prepares release"
      - "first commit"

release:
  github:
    owner: xsteadfastx
    name: iperf3exporter

archives:
  - format: tar.gz
    replacements:
      darwin: macos

  # - format: binary
  #   id: binary-archive
  #   replacements:
  #     darwin: macos

dockers:
  - dockerfile: build/package/docker/Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/xsteadfastx/iperf3exporter:latest
      - ghcr.io/xsteadfastx/iperf3exporter:{{ .Tag }}
      - ghcr.io/xsteadfastx/iperf3exporter:{{ .Major}}

nfpms:
  - formats:
      - apk
      - deb
      - rpm
    replacements:
      386: i386
    homepage: https://go.xsfx.dev/iperf3exporter
    maintainer: Marvin Preuss <marvin@xsteadfastx.org>
    dependencies:
      - iperf3
    bindir: /usr/local/bin
    contents:
      - src: init/openrc/iperf3exporter.init
        dst: /etc/init.d/iperf3exporter
        packager: apk
        file_info:
          mode: 0755
          owner: root
          group: root
      - src: init/systemd/iperf3exporter.service
        dst: /etc/systemd/system/iperf3exporter.service
        packager: deb
      - src: init/systemd/iperf3exporter.service
        dst: /etc/systemd/system/iperf3exporter.service
        packager: rpm
